<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */

/** @var \PayPal\Fastlane\ViewModel\InsightsViewModel $insightsViewModel */
$insightsViewModel = $block->getData('insights_view_model');

?>
<script type="text/x-magento-init">
{
    "*": {
        "PayPal_Fastlane/js/insights-checkout": {
            "clientId": "<?= /* @noEscape */ $insightsViewModel->getClientId() ?>"
        }
    }
}
</script>
