<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */

/** @var \PayPal\Fastlane\ViewModel\InsightsViewModel $insightsViewModel */
$insightsViewModel = $block->getData('insights_view_model');
/** @var \PayPal\Fastlane\ViewModel\CheckoutSuccess $orderViewViewModel */
$orderViewViewModel = $block->getData('order_view_view_model');

$getLastOrderData = $orderViewViewModel->getLastOrderData();

if ($getLastOrderData['maskedId'] !== ''):
?>

<script type="text/x-magento-init">
{
    "*": {
        "PayPal_Fastlane/js/insights-success": {
            "clientId": "<?= /* @noEscape */ $insightsViewModel->getClientId() ?>",
            "order": <?= /* @noEscape */ json_encode($getLastOrderData) ?>
        }
    }
}
</script>

<?php
endif;
?>
