<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */

/** @var \PayPal\Fastlane\ViewModel\BraintreeConfig $brainteeConfigViewModel */
$brainteeConfigViewModel = $block->getData('braintree_config_view_model');
/** @var \PayPal\Fastlane\ViewModel\CheckoutSuccess $orderViewViewModel */
$orderViewViewModel = $block->getData('order_view_view_model');

$getLastOrderData = $orderViewViewModel->getLastOrderData();

if ($getLastOrderData['maskedId'] !== ''):
?>

<script type="text/x-magento-init">
{
    "*": {
        "PayPal_Fastlane/js/insights-success": {
            "merchantId": "<?= /* @noEscape */ $brainteeConfigViewModel->getMerchantId() ?>",
            "order": <?= /* @noEscape */ json_encode($getLastOrderData) ?>
        }
    }
}
</script>

<?php
endif;
?>
